name: Reaxtica
channels:
  - conda-forge
  - defaults
dependencies:
  - joblib=1.1.0
  - networkx=2.4
  - numpy=1.21.5
  - openbabel=3.1.1
  - pandas=0.23.4
  - python=3.7.6
  - rdkit=2021.03.2
  - scikit-learn=0.23.1
  - tqdm=4.62.3
  - xgboost=1.5.0
- pip:
    - qmdesc==1.0.6